# Generated by Django 3.1.2 on 2020-10-19 00:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfootball', '0003_auto_20201019_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sunday',
            name='list_data',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
