# Generated by Django 3.1.2 on 2020-10-19 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfootball', '0005_auto_20201019_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sunday',
            name='list_data',
            field=models.CharField(max_length=100),
        ),
    ]
