# Generated by Django 3.1.2 on 2020-10-19 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfootball', '0002_monday_win'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monday',
            name='list_data',
            field=models.CharField(max_length=100),
        ),
    ]
