# Generated by Django 3.1.2 on 2020-10-19 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_project_win'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='list_data',
            field=models.CharField(max_length=100),
        ),
    ]
