# Generated by Django 3.1.1 on 2020-10-01 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegasbook', '0002_monday'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Monday',
        ),
        migrations.AddField(
            model_name='project',
            name='list_total',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
