# Generated by Django 3.1.1 on 2020-10-08 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vegasbook', '0003_auto_20201001_0829'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
